/* -------------------------------------------------------
PIZZA RUNNER CASE STUDY: SECTION C
INGREDIENT OPTIMISATION
-------------------------------------------------------
*/

-- 01: WHAT ARE THE STANDARD INGREDIENTS FOR EACH PIZZA?
-- COMPATIBILITY: MYSQL 8.0+, MARIADB 10.6+
-- GOAL: EXPAND COMMA-SEPARATED TOPPINGS INTO A CLEAN, ALPHABETIZED LIST PER PIZZA.

WITH PIZZA_TOPPINGS_EXPANDED AS (
    SELECT 
        PR.PIZZA_ID,
        -- TRIM HANDLES ANY RESIDUAL WHITESPACE AFTER THE SPLIT
        TRIM(JT.TOPPING_ID) AS TOPPING_ID
    FROM PIZZA_RECIPES AS PR
    CROSS JOIN JSON_TABLE(
        -- NESTED REPLACE STRIPS ALL SPACES TO ENSURE CLEAN JSON ARRAY FORMATTING
        CONCAT('["', REPLACE(REPLACE(TOPPINGS, ' ', ''), ',', '","'), '"]'),
        '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')
    ) AS JT
)
SELECT 
    PN.PIZZA_NAME,
    -- GROUP_CONCAT WITH ORDER BY ENSURES CONSISTENT, READABLE OUTPUT
    GROUP_CONCAT(
        DISTINCT PT.TOPPING_NAME 
        ORDER BY PT.TOPPING_NAME ASC 
        SEPARATOR ', '
    ) AS STANDARD_TOPPINGS
FROM PIZZA_TOPPINGS_EXPANDED AS PTE
JOIN PIZZA_NAMES AS PN    ON PN.PIZZA_ID = PTE.PIZZA_ID
JOIN PIZZA_TOPPINGS AS PT ON PTE.TOPPING_ID = PT.TOPPING_ID 
GROUP BY PN.PIZZA_NAME;

-- 2: WHAT WAS THE MOST COMMONLY ADDED EXTRA?

WITH CTE_EXTRAS AS (
    SELECT 
        CO.ORDER_ID, 
        CO.CUSTOMER_ID, 
        CO.PIZZA_ID, 
        CO.EXCLUSIONS,
        CJ.EXTRAS AS TOPPING_ID,
        CO.ORDER_TIME
    FROM CUSTOMER_ORDERS AS CO
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXTRAS, ", ", '","'), '"]'),
        '$[*]' COLUMNS (EXTRAS TEXT PATH '$')
    ) AS CJ
)
SELECT 
    PT.TOPPING_NAME, 
    COUNT(CE.TOPPING_ID) AS TOTAL_ADDITIONS
FROM CTE_EXTRAS AS CE
JOIN PIZZA_TOPPINGS AS PT ON CE.TOPPING_ID = PT.TOPPING_ID
GROUP BY PT.TOPPING_NAME
ORDER BY TOTAL_ADDITIONS DESC;


-- 3: WHAT WAS THE MOST COMMON EXCLUSION?

WITH CTE_EXCLUSIONS AS (
    SELECT 
        CO.ORDER_ID, 
        CO.CUSTOMER_ID, 
        CO.PIZZA_ID, 
        CO.EXTRAS,
        CJ.EXCLUSIONS AS TOPPING_ID,
        CO.ORDER_TIME
    FROM CUSTOMER_ORDERS AS CO
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXCLUSIONS, ", ", '","'), '"]'),
        '$[*]' COLUMNS (EXCLUSIONS TEXT PATH '$')
    ) AS CJ
)
SELECT 
    PT.TOPPING_NAME, 
    COUNT(CX.TOPPING_ID) AS TOTAL_EXCLUSIONS
FROM CTE_EXCLUSIONS AS CX
JOIN PIZZA_TOPPINGS AS PT ON CX.TOPPING_ID = PT.TOPPING_ID
GROUP BY PT.TOPPING_NAME
ORDER BY TOTAL_EXCLUSIONS DESC;

-- 4: GENERATE AN ORDER ITEM FOR EACH RECORD IN THE CUSTOMERS_ORDERS TABLE IN THE FORMAT OF ONE OF THE FOLLOWING:
-- MEAT LOVERS
-- MEAT LOVERS - EXCLUDE BEEF
-- MEAT LOVERS - EXTRA BACON
-- MEAT LOVERS - EXCLUDE CHEESE, BACON - EXTRA MUSHROOM, PEPPERS

WITH UNIQUE_CTE AS (
    SELECT *,
           ROW_NUMBER() OVER() AS RECORD_ID
    FROM CUSTOMER_ORDERS
),
EXTRA_CTE AS (
    SELECT UC.RECORD_ID, 
           GROUP_CONCAT(PT.TOPPING_NAME SEPARATOR ', ') AS EXTRA_NAMES
    FROM UNIQUE_CTE AS UC
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXTRAS, ', ', '","'), '"]'),
        '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')) AS JT
    JOIN PIZZA_TOPPINGS AS PT ON JT.TOPPING_ID = PT.TOPPING_ID
    GROUP BY UC.RECORD_ID
),
EXCLUSIONS_CTE AS (
    SELECT UC.RECORD_ID, 
           GROUP_CONCAT(PT.TOPPING_NAME SEPARATOR ', ') AS EXCLUSION_NAMES
    FROM UNIQUE_CTE AS UC
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXCLUSIONS, ', ', '","'), '"]'),
        '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')) AS JT
    JOIN PIZZA_TOPPINGS AS PT ON JT.TOPPING_ID = PT.TOPPING_ID
    GROUP BY UC.RECORD_ID
)
SELECT UC.RECORD_ID, 
       UC.ORDER_ID,
       CONCAT(PN.PIZZA_NAME,
              COALESCE(CONCAT(' - EXTRA ', EXTRA_NAMES), ''),
              COALESCE(CONCAT(' - EXCLUSIONS ', EXCLUSION_NAMES), '')
       ) AS ORDER_ITEM_DESCRIPTION
FROM UNIQUE_CTE AS UC
JOIN PIZZA_NAMES AS PN ON UC.PIZZA_ID = PN.PIZZA_ID
LEFT JOIN EXCLUSIONS_CTE AS EXC ON UC.RECORD_ID = EXC.RECORD_ID
LEFT JOIN EXTRA_CTE AS EXT ON UC.RECORD_ID = EXT.RECORD_ID
ORDER BY UC.ORDER_ID;

-- 5: GENERATE AN ALPHABETICALLY ORDERED COMMA SEPARATED INGREDIENT LIST FOR EACH PIZZA ORDER FROM THE CUSTOMER_ORDERS TABLE AND 
-- ADD A 2X IN FRONT OF ANY RELEVANT INGREDIENTS
-- FOR EXAMPLE: "MEAT LOVERS: 2XBACON, BEEF, ... , SALAMI"

WITH UNIQUE_CTE AS (
    SELECT *,
           ROW_NUMBER() OVER() AS RECORD_ID
    FROM CUSTOMER_ORDERS
),
EXTRA_CTE AS (
    SELECT RECORD_ID, 
           PT.TOPPING_NAME AS EXTRA_NAMES
    FROM UNIQUE_CTE AS UCT
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXTRAS, ', ', '","'), '"]'),
        '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')) AS JT
    JOIN PIZZA_TOPPINGS AS PT ON JT.TOPPING_ID = PT.TOPPING_ID
),
EXCLUSION_CTE AS (
    SELECT RECORD_ID, 
           PT.TOPPING_NAME AS EXCLUSION_NAMES
    FROM UNIQUE_CTE AS UCT
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXCLUSIONS, ', ', '","'), '"]'),
        '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')) AS JT
    JOIN PIZZA_TOPPINGS AS PT ON JT.TOPPING_ID = PT.TOPPING_ID
),
RECIPE_CTE AS (
    SELECT PIZZA_ID, 
           PT.TOPPING_NAME AS TOPPINGS
    FROM PIZZA_RECIPES AS PRE
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(TOPPINGS, ', ', '","'), '"]'),
        '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')) AS JT
    JOIN PIZZA_TOPPINGS AS PT ON PT.TOPPING_ID = JT.TOPPING_ID
)
SELECT UCT.RECORD_ID, 
       GROUP_CONCAT(
           CASE 
               WHEN EXT.EXTRA_NAMES IS NOT NULL THEN CONCAT('2X ', REC.TOPPINGS) 
               ELSE REC.TOPPINGS 
           END 
           ORDER BY REC.TOPPINGS ASC 
           SEPARATOR ', '
       ) AS FINAL_INGREDIENTS
FROM UNIQUE_CTE AS UCT
JOIN RECIPE_CTE AS REC ON UCT.PIZZA_ID = REC.PIZZA_ID
LEFT JOIN EXTRA_CTE AS EXT ON UCT.RECORD_ID = EXT.RECORD_ID AND EXT.EXTRA_NAMES = REC.TOPPINGS
LEFT JOIN EXCLUSION_CTE AS ECT ON UCT.RECORD_ID = ECT.RECORD_ID AND ECT.EXCLUSION_NAMES = REC.TOPPINGS
WHERE ECT.EXCLUSION_NAMES IS NULL
GROUP BY UCT.RECORD_ID;
