/* -------------------------------------------------------
PIZZA RUNNER CASE STUDY: SECTION C
INGREDIENT OPTIMISATION
-------------------------------------------------------
*/

-- 01: WHAT ARE THE STANDARD INGREDIENTS FOR EACH PIZZA?
-- COMPATIBILITY: MYSQL 8.0+, MARIADB 10.6+
-- GOAL: EXPAND COMMA-SEPARATED TOPPINGS INTO A CLEAN, ALPHABETIZED LIST PER PIZZA.

WITH PIZZA_TOPPINGS_EXPANDED AS (
    SELECT 
        PR.PIZZA_ID,
        -- TRIM HANDLES ANY RESIDUAL WHITESPACE AFTER THE SPLIT
        TRIM(JT.TOPPING_ID) AS TOPPING_ID
    FROM PIZZA_RECIPES AS PR
    CROSS JOIN JSON_TABLE(
        -- NESTED REPLACE STRIPS ALL SPACES TO ENSURE CLEAN JSON ARRAY FORMATTING
        CONCAT('["', REPLACE(REPLACE(TOPPINGS, ' ', ''), ',', '","'), '"]'),
        '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')
    ) AS JT
)
SELECT 
    PN.PIZZA_NAME,
    -- GROUP_CONCAT WITH ORDER BY ENSURES CONSISTENT, READABLE OUTPUT
    GROUP_CONCAT(
        DISTINCT PT.TOPPING_NAME 
        ORDER BY PT.TOPPING_NAME ASC 
        SEPARATOR ', '
    ) AS STANDARD_TOPPINGS
FROM PIZZA_TOPPINGS_EXPANDED AS PTE
JOIN PIZZA_NAMES AS PN    ON PN.PIZZA_ID = PTE.PIZZA_ID
JOIN PIZZA_TOPPINGS AS PT ON PTE.TOPPING_ID = PT.TOPPING_ID 
GROUP BY PN.PIZZA_NAME;

-- 2: WHAT WAS THE MOST COMMONLY ADDED EXTRA?

WITH CTE_EXTRAS AS (
    SELECT 
        CO.ORDER_ID, 
        CO.CUSTOMER_ID, 
        CO.PIZZA_ID, 
        CO.EXCLUSIONS,
        CJ.EXTRAS AS TOPPING_ID,
        CO.ORDER_TIME
    FROM CUSTOMER_ORDERS AS CO
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXTRAS, ", ", '","'), '"]'),
        '$[*]' COLUMNS (EXTRAS TEXT PATH '$')
    ) AS CJ
)
SELECT 
    PT.TOPPING_NAME, 
    COUNT(CE.TOPPING_ID) AS TOTAL_ADDITIONS
FROM CTE_EXTRAS AS CE
JOIN PIZZA_TOPPINGS AS PT ON CE.TOPPING_ID = PT.TOPPING_ID
GROUP BY PT.TOPPING_NAME
ORDER BY TOTAL_ADDITIONS DESC;


-- 3: WHAT WAS THE MOST COMMON EXCLUSION?

WITH CTE_EXCLUSIONS AS (
    SELECT 
        CO.ORDER_ID, 
        CO.CUSTOMER_ID, 
        CO.PIZZA_ID, 
        CO.EXTRAS,
        CJ.EXCLUSIONS AS TOPPING_ID,
        CO.ORDER_TIME
    FROM CUSTOMER_ORDERS AS CO
    CROSS JOIN JSON_TABLE(
        CONCAT('["', REPLACE(EXCLUSIONS, ", ", '","'), '"]'),
        '$[*]' COLUMNS (EXCLUSIONS TEXT PATH '$')
    ) AS CJ
)
SELECT 
    PT.TOPPING_NAME, 
    COUNT(CX.TOPPING_ID) AS TOTAL_EXCLUSIONS
FROM CTE_EXCLUSIONS AS CX
JOIN PIZZA_TOPPINGS AS PT ON CX.TOPPING_ID = PT.TOPPING_ID
GROUP BY PT.TOPPING_NAME
ORDER BY TOTAL_EXCLUSIONS DESC;
