-- D. PRICING AND RATINGS
-- 1: IF A MEAT LOVERS PIZZA COSTS $12 AND VEGETARIAN COSTS $10 AND THERE WERE NO CHARGES FOR CHANGES 
-- HOW MUCH MONEY HAS PIZZA RUNNER MADE SO FAR IF THERE ARE NO DELIVERY FEES?

SELECT SUM(CASE WHEN CO.PIZZA_ID = 1 THEN 12 ELSE 10 END) AS TOTAL_INCOME
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID 
JOIN PIZZA_NAMES AS PN ON CO.PIZZA_ID = PN.PIZZA_ID
WHERE CANCELLATION IS NULL;

-- 2: WHAT IF THERE WAS AN ADDITIONAL $1 CHARGE FOR ANY PIZZA EXTRAS?
-- ADD CHEESE IS $1 EXTRA

WITH UNIQUE_CTE AS(
	SELECT *,
		ROW_NUMBER() OVER() AS RECORD_ID
    FROM CUSTOMER_ORDERS    
),
EXTRA_CTE AS(
	SELECT UC.RECORD_ID, PT.TOPPING_NAME AS EXTRA_NAMES
    FROM UNIQUE_CTE AS UC
    CROSS JOIN JSON_TABLE(
	CONCAT('["',REPLACE(EXTRAS, ', ', '","'), '"]'),
    '$[*]' COLUMNS (TOPPING_ID TEXT PATH '$')) AS JT
    JOIN PIZZA_TOPPINGS AS PT ON PT.TOPPING_ID = JT.TOPPING_ID
),
TOTAL_INCOME_CTE AS(
	SELECT SUM(CASE WHEN UC.PIZZA_ID = 1 THEN 12 ELSE 10 END) AS TOTAL_INCOME
FROM UNIQUE_CTE AS UC
JOIN RUNNER_ORDERS AS RO ON UC.ORDER_ID = RO.ORDER_ID 
JOIN PIZZA_NAMES AS PN ON UC.PIZZA_ID = PN.PIZZA_ID
WHERE CANCELLATION IS NULL

UNION ALL

SELECT SUM(CASE WHEN EXTRA_NAMES = 'CHEESE' THEN 1 ELSE 0 END) AS TOTAL_INCOME
FROM EXTRA_CTE)
SELECT SUM(TOTAL_INCOME) AS GRAND_TOTAL
FROM TOTAL_INCOME_CTE;

-- 3: THE PIZZA RUNNER TEAM NOW WANTS TO ADD AN ADDITIONAL RATINGS SYSTEM THAT ALLOWS CUSTOMERS TO RATE THEIR RUNNER, 
-- HOW WOULD YOU DESIGN AN ADDITIONAL TABLE FOR THIS NEW DATASET - GENERATE A SCHEMA FOR THIS NEW TABLE 
-- AND INSERT YOUR OWN DATA FOR RATINGS FOR EACH SUCCESSFUL CUSTOMER ORDER BETWEEN 1 TO 5.

ALTER TABLE RUNNER_ORDERS 
MODIFY COLUMN ORDER_ID INT NOT NULL PRIMARY KEY;

CREATE TABLE RATINGS(
RATING_ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_ID INT NOT NULL,
RATING INT NOT NULL CHECK (RATING BETWEEN 1 AND 5),
FOREIGN KEY (ORDER_ID) REFERENCES RUNNER_ORDERS(ORDER_ID) ON DELETE CASCADE
);

INSERT INTO RATINGS(ORDER_ID, RATING)
SELECT ORDER_ID, FLOOR(4 + RAND() * 2)
FROM RUNNER_ORDERS 
WHERE CANCELLATION IS NULL
AND ORDER_ID IS NOT NULL;


-- 4: USING YOUR NEWLY GENERATED TABLE - CAN YOU JOIN ALL OF THE INFORMATION TOGETHER TO FORM A TABLE 
-- WHICH HAS THE FOLLOWING INFORMATION FOR SUCCESSFUL DELIVERIES?
-- CUSTOMER_ID
-- ORDER_ID
-- RUNNER_ID
-- RATING
-- ORDER_TIME
-- PICKUP_TIME
-- TIME BETWEEN ORDER AND PICKUP
-- DELIVERY DURATION
-- AVERAGE SPEED
-- TOTAL NUMBER OF PIZZAS

CREATE TABLE IF NOT EXISTS MASTER_TABLE(
CUSTOMER_ID INT,
ORDER_ID INT,
RUNNER_ID INT,
RATING INT,
ORDER_TIME TIMESTAMP,
PICKUP_TIME TIMESTAMP,
TIME_BETWEEN INT,
DURATION_MIN INT,
AVERAGE_SPEED FLOAT4,
TOTAL_PIZZAS INT
);

INSERT INTO MASTER_TABLE(CUSTOMER_ID, ORDER_ID, RUNNER_ID, RATING, ORDER_TIME, PICKUP_TIME, TIME_BETWEEN, DURATION_MIN, AVERAGE_SPEED, TOTAL_PIZZAS)
SELECT CO.CUSTOMER_ID, RO.ORDER_ID, RO.RUNNER_ID, RA.RATING, CO.ORDER_TIME, RO.PICKUP_TIME, 
	TIMESTAMPDIFF(MINUTE, ORDER_TIME, PICKUP_TIME) AS TIME_BETWEEN, RO.DURATION_MIN,
    ROUND(DISTANCE_KM/DURATION_MIN*60,2) AS AVERAGE_SPEED, COUNT(CO.PIZZA_ID) AS TOTAL_PIZZAS
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID
JOIN RATINGS AS RA ON RO.ORDER_ID = RA.ORDER_ID
WHERE CANCELLATION IS NULL
GROUP BY CO.CUSTOMER_ID, RO.ORDER_ID, RO.RUNNER_ID, RA.RATING, CO.ORDER_TIME, RO.PICKUP_TIME, RO.DURATION_MIN, RO.DISTANCE_KM;


-- 5: IF A MEAT LOVERS PIZZA WAS $12 AND VEGETARIAN $10 FIXED PRICES WITH NO COST FOR EXTRAS AND EACH RUNNER IS PAID $0.30 PER KILOMETRE TRAVELED 
-- HOW MUCH MONEY DOES PIZZA RUNNER HAVE LEFT OVER AFTER THESE DELIVERIES?

WITH TOTAL_AMOUNT_CTE AS(
SELECT SUM(CASE WHEN CO.PIZZA_ID = 1 THEN 12 ELSE 10 END) AS TOTAL_AMOUNT
FROM RUNNER_ORDERS AS RO
JOIN CUSTOMER_ORDERS AS CO ON RO.ORDER_ID = CO.ORDER_ID
WHERE CANCELLATION IS NULL
),
RUNNER_CTE AS
(SELECT ROUND(SUM(DISTANCE_KM) * 0.30, 2) AS RUNNER_PAYMENT
FROM RUNNER_ORDERS
WHERE CANCELLATION IS NULL
)
SELECT TAC.TOTAL_AMOUNT, RC.RUNNER_PAYMENT, TAC.TOTAL_AMOUNT - RC.RUNNER_PAYMENT AS LEFT_OVER
FROM TOTAL_AMOUNT_CTE AS TAC
CROSS JOIN RUNNER_CTE AS RC;
