-- BONUS Question
-- IF DANNY WANTS TO EXPAND HIS RANGE OF PIZZAS - HOW WOULD THIS IMPACT THE EXISTING DATA DESIGN? 
-- WRITE AN INSERT STATEMENT TO DEMONSTRATE WHAT WOULD HAPPEN IF A NEW SUPREME PIZZA 
-- WITH ALL THE TOPPINGS WAS ADDED TO THE PIZZA RUNNER MENU?

-- 1. ADD THE NEW PIZZA ENTITY TO THE NAMES TABLE
INSERT INTO PIZZA_NAMES(PIZZA_ID, PIZZA_NAME) VALUES
(3, 'SUPREME');

-- 2. MAP THE RECIPE WITH ALL AVAILABLE TOPPINGS (1-12)
INSERT INTO PIZZA_RECIPES(PIZZA_ID, TOPPINGS) VALUES
(3, '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12');

-- EXPLANATION OF IMPACT:
-- THIS APPROACH DEMONSTRATES THE SCALABILITY OF A WELL-STRUCTURED RELATIONAL DATABASE. 
-- THE IMPACT IS MINIMAL DUE TO THE FOLLOWING ARCHITECTURAL STRENGTHS:
-- ROW-BASED GROWTH (DML VS. DDL): WE DO NOT NEED TO ALTER THE TABLE STRUCTURE OR ADD NEW COLUMNS TO EXPAND THE MENU. 
-- ADDING NEW PRODUCTS IS HANDLED ENTIRELY THROUGH DATA INSERTION (DML), WHICH PREVENTS DATABASE DOWNTIME AND KEEPS THE SCHEMA STABLE.
-- FORWARD COMPATIBILITY: BECAUSE THE ANALYTICS LOGIC (REVENUE, RUNNER PERFORMANCE, AND THE MASTER_TABLE) IS DECOUPLED FROM THE PRODUCT DEFINITIONS, 
-- THE SYSTEM WILL AUTOMATICALLY RECOGNIZE AND INCLUDE THE 'SUPREME' PIZZA WITHOUT ANY CODE MODIFICATIONS.
-- DATA INTEGRITY: THE DESIGN MAINTAINS A "SINGLE SOURCE OF TRUTH" BY MAPPING UNIQUE PIZZA IDS TO SPECIFIC RECIPES. 
-- THIS ALLOWS FOR UNLIMITED MENU EXPANSION WHILE ENSURING THAT HISTORICAL DATA AND NEW ORDERS REMAIN CONSISTENT.
