-- =============================================================================
-- STEP 1: DATA AUDIT - IDENTIFYING DUPLICATES IN CUSTOMER_ORDERS
-- =============================================================================

-- APPROACH A: USING WINDOW FUNCTIONS (ROW_NUMBER)
-- THIS IS A MODERN, FLEXIBLE APPROACH THAT IDENTIFIES SPECIFIC ROWS TO TARGET.
SELECT * FROM ( 
  SELECT *,
  ROW_NUMBER() OVER(PARTITION BY ORDER_ID, CUSTOMER_ID, PIZZA_ID, EXCLUSIONS, EXTRAS, ORDER_TIME) AS RANKINGS
  FROM CUSTOMER_ORDERS
) AS RANKINGS_CUSTOMER
WHERE RANKINGS >= 2;

-- APPROACH B: USING GROUP BY AND HAVING
-- THIS IS A CLASSIC AGGREGATION APPROACH TO QUICKLY COUNT HOW MANY TIMES A RECORD REPEATS.
SELECT ORDER_ID, CUSTOMER_ID, PIZZA_ID, EXCLUSIONS, EXTRAS, ORDER_TIME, COUNT(*)
FROM CUSTOMER_ORDERS
GROUP BY ORDER_ID, CUSTOMER_ID, PIZZA_ID, EXCLUSIONS, EXTRAS, ORDER_TIME
HAVING COUNT(*) > 1;

-- BUSINESS VALIDATION: JOINING WITH RUNNER_ORDERS
-- CHECKING IF DUPLICATE DATA IN CUSTOMER_ORDERS (ORDER_ID 4) REPRESENTS A REAL MULTI-ITEM ORDER.
SELECT *
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO
ON CO.ORDER_ID = RO.ORDER_ID
WHERE CO.ORDER_ID = 4;


-- =============================================================================
-- STEP 2: CLEANING NULLS AND BLANKS IN CUSTOMER_ORDERS
-- =============================================================================

-- VERIFICATION: LOCATING ROWS WITH STRING 'NULL' OR EMPTY VALUES IN EXTRAS.
SELECT * FROM CUSTOMER_ORDERS
WHERE EXTRAS = '' OR EXTRAS = 'NULL';

-- EXECUTION: REPLACING STRINGS WITH ACTUAL DATABASE NULLS FOR EXTRAS.
UPDATE CUSTOMER_ORDERS
SET EXTRAS = NULL
WHERE EXTRAS = '' OR EXTRAS = 'NULL';

-- VERIFICATION: LOCATING ROWS WITH STRING 'NULL' OR EMPTY VALUES IN EXCLUSIONS.
SELECT * FROM CUSTOMER_ORDERS
WHERE EXCLUSIONS = '' OR EXCLUSIONS = 'NULL';

-- EXECUTION: REPLACING STRINGS WITH ACTUAL DATABASE NULLS FOR EXCLUSIONS.
UPDATE CUSTOMER_ORDERS
SET EXCLUSIONS = NULL
WHERE EXCLUSIONS = '' OR EXCLUSIONS = 'NULL';


-- =============================================================================
-- STEP 3: CLEANING RUNNER_ORDERS
-- =============================================================================

-- VERIFICATION: CHECKING FOR DUPLICATES IN RUNNER_ORDERS USING THE WINDOW FUNCTION APPROACH.
SELECT *,
 ROW_NUMBER() OVER(PARTITION BY ORDER_ID, RUNNER_ID, PICKUP_TIME, DISTANCE, DURATION, CANCELLATION) AS RANKING
FROM RUNNER_ORDERS;

-- VERIFICATION: CHECKING FOR MESSY PICKUP_TIME DATA.
SELECT * FROM RUNNER_ORDERS
WHERE PICKUP_TIME = 'NULL' OR PICKUP_TIME = '';

-- VALIDATION: COUNTING ROWS AFFECTED BEFORE UPDATING.
SELECT COUNT(*) FROM RUNNER_ORDERS
WHERE PICKUP_TIME = 'NULL' OR PICKUP_TIME = '';

-- EXECUTION: CLEANING PICKUP_TIME.
UPDATE RUNNER_ORDERS
SET PICKUP_TIME = NULL
WHERE PICKUP_TIME = 'NULL' OR PICKUP_TIME = '';

-- VERIFICATION: CHECKING FOR MESSY DISTANCE DATA.
SELECT * FROM RUNNER_ORDERS
WHERE DISTANCE = 'NULL' OR DISTANCE = '';

-- EXECUTION: CLEANING DISTANCE.
UPDATE RUNNER_ORDERS
SET DISTANCE = NULL
WHERE DISTANCE = 'NULL' OR DISTANCE = '';

-- VERIFICATION: CHECKING FOR MESSY DURATION DATA.
SELECT * FROM RUNNER_ORDERS
WHERE DURATION = 'NULL' OR DURATION = '';

-- EXECUTION: CLEANING DURATION.
UPDATE RUNNER_ORDERS
SET DURATION = NULL
WHERE DURATION = 'NULL' OR DURATION = '';

-- VERIFICATION: CHECKING FOR MESSY CANCELLATION DATA.
SELECT * FROM RUNNER_ORDERS
WHERE CANCELLATION = 'NULL' OR CANCELLATION = '';

-- EXECUTION: CLEANING CANCELLATION.
UPDATE RUNNER_ORDERS
SET CANCELLATION = NULL
WHERE CANCELLATION = 'NULL' OR CANCELLATION = '';


-- =============================================================================
-- STEP 4: DATA STANDARDIZATION & TYPE CASTING
-- =============================================================================

-- SCHEMA UPDATE: CONVERTING PICKUP_TIME TO PROPER TIMESTAMP FORMAT.
ALTER TABLE RUNNER_ORDERS
MODIFY COLUMN PICKUP_TIME TIMESTAMP;

-- VERIFICATION: TESTING DURATION STRING MANIPULATION BEFORE APPLYING CHANGES.
-- REMOVES 'M', 'MINS', 'MINUTES' BY FINDING THE FIRST SPACE OR CHARACTER.
SELECT DURATION,
	CASE
		WHEN DURATION LIKE '%M%' THEN TRIM(SUBSTRING(REPLACE(DURATION, 'M', ' '),1, LOCATE(' ', REPLACE(DURATION, 'M', ' ')) - 1))
        ELSE DURATION 
        END AS RE
FROM RUNNER_ORDERS;        

-- EXECUTION: UPDATING DURATION TO BE NUMERIC ONLY.
UPDATE RUNNER_ORDERS
SET DURATION = TRIM(SUBSTRING(REPLACE(DURATION, 'M', ' '),1, LOCATE(' ', REPLACE(DURATION, 'M', ' ')) - 1))
WHERE DURATION LIKE '%M%';

-- SCHEMA UPDATE: CONVERTING DURATION TO INTEGER FOR CALCULATIONS.
ALTER TABLE RUNNER_ORDERS
MODIFY COLUMN DURATION INT;

-- VERIFICATION: TESTING DISTANCE STRING MANIPULATION BEFORE APPLYING CHANGES.
-- REMOVES 'KM' SUFFIX.
SELECT DISTANCE,
	CASE
		WHEN DISTANCE LIKE '%K%' THEN TRIM(SUBSTRING(REPLACE(DISTANCE,'K', ' '), 1, LOCATE(' ',REPLACE(DISTANCE,'K', ' '))-1))
		ELSE DISTANCE
        END AS DIS
FROM RUNNER_ORDERS;

-- EXECUTION: UPDATING DISTANCE TO BE NUMERIC ONLY.
UPDATE RUNNER_ORDERS
SET DISTANCE = TRIM(SUBSTRING(REPLACE(DISTANCE,'K', ' '), 1, LOCATE(' ',REPLACE(DISTANCE,'K', ' '))-1))
WHERE DISTANCE LIKE '%K%';

-- SCHEMA UPDATE: CONVERTING DISTANCE TO FLOAT FOR PRECISION (E.G., 13.4KM).
ALTER TABLE RUNNER_ORDERS
MODIFY COLUMN DISTANCE FLOAT4;

-- FINAL STEP: RENAMING COLUMNS TO INCLUDE UNITS FOR BETTER READABILITY AND CLARITY.
ALTER TABLE RUNNER_ORDERS
RENAME COLUMN DISTANCE TO DISTANCE_KM; 

ALTER TABLE RUNNER_ORDERS
RENAME COLUMN DURATION TO DURATION_MIN;
