-- ============================================================
-- B. Data Analysis Questions
-- ============================================================
 
-- 1: HOW MANY CUSTOMERS HAS FOODIE-FI EVER HAD?

SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SUBSCRIPTIONS;

-- 2: WHAT IS THE MONTHLY DISTRIBUTION OF TRIAL PLAN START_DATE VALUES FOR OUR DATASET 
-- USE THE START OF THE MONTH AS THE GROUP BY VALUE 

SELECT DATE_FORMAT(START_DATE, '%Y-%m-01') AS MONTH_START,COUNT(*) AS TOTAL_TRIAL_PLANS
FROM SUBSCRIPTIONS
WHERE PLAN_ID = 0
GROUP BY MONTH_START;


-- 3: WHAT PLAN START_DATE VALUES OCCUR AFTER THE YEAR 2020 FOR OUR DATASET? SHOW THE BREAKDOWN BY COUNT OF EVENTS FOR EACH PLAN_NAME

SELECT P.PLAN_NAME, COUNT(SUB.PLAN_ID) AS COUNT_OF_EVENTS
FROM SUBSCRIPTIONS AS SUB
JOIN PLANS AS P ON SUB.PLAN_ID = P.PLAN_ID
WHERE START_DATE >= '2021-01-01'
GROUP BY P.PLAN_NAME
ORDER BY COUNT_OF_EVENTS DESC;

-- 4: WHAT IS THE CUSTOMER COUNT AND PERCENTAGE OF CUSTOMERS WHO HAVE CHURNED ROUNDED TO 1 DECIMAL PLACE?

WITH PERCENTAGE_CTE AS(
SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMER, SUM(CASE WHEN PLAN_ID = 4 THEN 1 ELSE 0 END) AS CHURNED_CUSTOMER
FROM SUBSCRIPTIONS)
SELECT TOTAL_CUSTOMER, ROUND((CHURNED_CUSTOMER/TOTAL_CUSTOMER) * 100, 1) AS CUSTOMER_PERCENT
FROM PERCENTAGE_CTE;

-- 5: HOW MANY CUSTOMERS HAVE CHURNED STRAIGHT AFTER THEIR INITIAL FREE TRIAL - WHAT PERCENTAGE IS THIS ROUNDED TO THE NEAREST WHOLE NUMBER?

WITH ROW_CTE AS 
(SELECT *, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY START_DATE) AS ROW_NUM
FROM SUBSCRIPTIONS),
CHURNED_CTE AS
(SELECT COUNT(*) AS CHURNED_CUSTOMER
FROM ROW_CTE 
WHERE ROW_NUM = 2 AND PLAN_ID = 4),
TOTAL_CTE AS
(SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMER
FROM SUBSCRIPTIONS)
SELECT CHURNED_CUSTOMER, FLOOR((CHURNED_CUSTOMER/ TOTAL_CUSTOMER) * 100.0) AS PERCENT
FROM TOTAL_CTE 
JOIN CHURNED_CTE;

-- 6: WHAT IS THE NUMBER AND PERCENTAGE OF CUSTOMER PLANS AFTER THEIR INITIAL FREE TRIAL?

WITH ROW_CTE AS(
	SELECT CUSTOMER_ID, PLAN_ID, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY START_DATE) AS ROW_NUM
    FROM SUBSCRIPTIONS
)
SELECT P.PLAN_NAME, COUNT(RC.CUSTOMER_ID) AS TOTAL_PLANS, ROUND((COUNT(RC.CUSTOMER_ID)/1000) * 100.0, 2) AS PERCENT
FROM ROW_CTE AS RC
JOIN PLANS AS P ON RC.PLAN_ID = P.PLAN_ID 
WHERE RC.ROW_NUM = 2
GROUP BY P.PLAN_NAME;

-- 7: WHAT IS THE CUSTOMER COUNT AND PERCENTAGE BREAKDOWN OF ALL 5 PLAN_NAME VALUES AT 2020-12-31?

WITH ROW_CTE AS(
	SELECT CUSTOMER_ID, PLAN_ID, START_DATE, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY START_DATE DESC) AS ROW_NUM
    FROM SUBSCRIPTIONS
    WHERE START_DATE <= '2020-12-31'
)
SELECT P.PLAN_NAME, COUNT(RC.CUSTOMER_ID) AS CUSTOMER_COUNT, ROUND((COUNT(RC.CUSTOMER_ID)/1000) * 100.0, 1) AS PERCENT
FROM ROW_CTE AS RC
JOIN PLANS AS P ON RC.PLAN_ID = P.PLAN_ID
WHERE RC.ROW_NUM = 1
GROUP BY P.PLAN_NAME
ORDER BY CUSTOMER_COUNT DESC;

-- 8: HOW MANY CUSTOMERS HAVE UPGRADED TO AN ANNUAL PLAN IN 2020?

SELECT COUNT(*)
FROM SUBSCRIPTIONS
WHERE PLAN_ID = 3 AND 
	START_DATE <= '2020-12-31';

-- 9: HOW MANY DAYS ON AVERAGE DOES IT TAKE FOR A CUSTOMER TO AN ANNUAL PLAN FROM THE DAY THEY JOIN FOODIE-FI?

WITH JOIN_DATE_CTE AS(
	SELECT CUSTOMER_ID, START_DATE AS JOIN_DATE
    FROM SUBSCRIPTIONS
    WHERE PLAN_ID = 0
),
PLAN_DATE AS(
	SELECT CUSTOMER_ID, START_DATE AS ANNUAL_PLAN_DATE
    FROM SUBSCRIPTIONS
    WHERE PLAN_ID = 3
)
SELECT ROUND(AVG(DATEDIFF(ANNUAL_PLAN_DATE, JOIN_DATE)), 0) AS DAYS
FROM PLAN_DATE AS PD
JOIN JOIN_DATE_CTE AS JD ON PD.CUSTOMER_ID = JD.CUSTOMER_ID;


-- 10: CAN YOU FURTHER BREAKDOWN THIS AVERAGE VALUE INTO 30 DAY PERIODS (I.E. 0-30 DAYS, 31-60 DAYS ETC)

WITH JOIN_DATE_CTE AS(
	SELECT CUSTOMER_ID, START_DATE AS JOIN_DATE
    FROM SUBSCRIPTIONS
    WHERE PLAN_ID = 0
),
PLAN_DATE AS(
	SELECT CUSTOMER_ID, START_DATE AS ANNUAL_PLAN_DATE
    FROM SUBSCRIPTIONS
    WHERE PLAN_ID = 3
),
AVERAGE_CTE AS(
SELECT DATEDIFF(ANNUAL_PLAN_DATE, JOIN_DATE) AS DAYS
FROM PLAN_DATE AS PD
JOIN JOIN_DATE_CTE AS JD ON PD.CUSTOMER_ID = JD.CUSTOMER_ID)
SELECT 
	CONCAT(FLOOR(DAYS / 30) * 30, ' - ', (FLOOR(DAYS / 30) + 1) * 30, ' DAYS') AS BUCKET,
    COUNT(*) AS TOTAL
FROM AVERAGE_CTE
GROUP BY BUCKET
-- MIN() is an aggregate function — so MySQL accepts it in ORDER BY without needing it in GROUP BY.
-- Since all rows in the same bucket have the same FLOOR value anyway (e.g. all "30-60" rows have FLOOR = 1), 
-- MIN(FLOOR(days/30)) and MAX(FLOOR(days/30)) would return the same value. 
-- So MIN is just a trick to satisfy MySQL's ONLY_FULL_GROUP_BY rule(Error Code # 1055).
ORDER BY FLOOR(DAYS/ 30);

-- 11: HOW MANY CUSTOMERS DOWNGRADED FROM A PRO MONTHLY TO A BASIC MONTHLY PLAN IN 2020?

WITH PREVIOUS_CTE AS
(SELECT CUSTOMER_ID, PLAN_ID,
	LAG(PLAN_ID = 2) OVER(PARTITION BY CUSTOMER_ID ORDER BY START_DATE) AS PREVIOUS_VALUE
FROM SUBSCRIPTIONS
WHERE START_DATE <= '2020-12-31')
SELECT COUNT(*) AS TOTAL_CUSTOMER
FROM PREVIOUS_CTE
WHERE PLAN_ID = 1 AND PREVIOUS_VALUE = 1;
